@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>
!include DEVICONS/android.puml
!include DEVICONS/django.puml

title Components Diagram for MiCosecha

AddContainerTag("android", $sprite="android", $legendText="android container")
AddContainerTag("django", $sprite="django")
AddContainerTag("db", $sprite="database_server", $legendText="database container")


Container(mobile_app, "Android Application", "Kotlin","Allow users to view data related to factors that contribute to the planting of crops", $tags="android")

System_Boundary(mi_cosecha, "API Application"){
    Container(sign_in, "Sign in controller", "Allow users login with their email",  $tags="django")
    Container(register, "Register controller", "Allow users a registration in platform",  $tags="django")
    Container(graph_data, "Graph data controller", "Shows to a user graphs related with planting factors",  $tags="django")
}

ContainerDb(rel_db, "Relational Database", "MySQL", "Stores users and application data",  $tags="db")

System_Ext(data, "Data", "IDEAM and FEDEARROZ")

Rel(mobile_app, sign_in, "Uses", "GraphQL")
Rel(mobile_app, register, "Uses", "GraphQL")
Rel(mobile_app, graph_data, "Uses", "GraphQL")
Rel(graph_data, data, "Uses", "GraphQL")
Rel(sign_in, rel_db, "Uses", "GraphQL")
Rel(register, rel_db, "Uses", "GraphQL")

@enduml
