@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>
!include DEVICONS/android.puml
!include DEVICONS/python.puml

title Components Diagram for MiCosecha

AddContainerTag("android", $sprite="android", $legendText="android container")
AddContainerTag("python", $sprite="python", $legendText="python container")

Container(mobile_app, "Android Application", "Kotlin","Allow users to view data related to the factors that contribute to the planting of crops", $tags="android")

System_Boundary(mi_cosecha, "Requests processor"){
    System_Boundary(Chatbot_service, "Chatbot service"){
        Container(flask_chat, "Chatbot", "Chatbot used by the user to interact with the system",  $tags="python")
    }
    System_Boundary(Graph_service, "Graph service"){
        Container(flask_data, "Graph data", "Shows to a user graphs related with planting factors",  $tags="python")
    }
}

System_Ext(data, "Data", "Dataverse and FEDEARROZ")

mobile_app <--> flask_chat: Uses [HTTP]
mobile_app <--> flask_data: Uses [HTTP]
Rel_L(flask_data, data, "Uses", "HTTP")


@enduml
