@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>
!include DEVICONS/android.puml
!include DEVICONS/django.puml

title Container Diagram for MiCosecha

AddContainerTag("android", $sprite="android", $legendText="android container")
AddContainerTag("django", $sprite="django", $legendText="django container")
AddContainerTag("db", $sprite="database_server", $legendText="database container")

Person(user, "User", "Who needs to check\nplanting crops factors")

System_Boundary(mi_cosecha, "MiCosecha"){
    Container(mobile_app, "Android Application", "Kotlin","Allow users to view data related to factors that contribute to the planting of crops", $tags="android")
    ContainerDb(django, "API", "Django", "Handles all business logic",  $tags="django")
    ContainerDb(rel_db, "Relational Database", "MySQL", "Stores users and application data",  $tags="db")
}

System_Ext(datos_gov, "Data", "IDEAM and FEDEARROZ")

Rel(user, mobile_app, "Uses")
Rel(mobile_app, django, "Uses", "GraphQL")
Rel(django, rel_db, "Uses", "GraphQL")
Rel(django, datos_gov, "Uses", "GraphQL")

@enduml
