@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>
!include DEVICONS/android.puml
!include DEVICONS/python.puml

title Container Diagram for MiCosecha

AddContainerTag("android", $sprite="android", $legendText="android container")
AddContainerTag("python", $sprite="python", $legendText="python container")

Person(user, "User", "Who needs to check\nplanting crops factors")

System_Boundary(mi_cosecha, "MiCosecha"){
    Container(mobile_app, "Android Application", "Kotlin","Allow users to view data related to factors that contribute to the planting of crops", $tags="android")
    Container(flask_data, "Requests processor", "FLask", "Handles data processing logic", $tags="python")
}

System_Ext(datos_gov, "Data", "Instituto de Hidrología - CIAT Dataverse")

Rel_R(user, mobile_app, "Uses")
mobile_app <--> flask_data: Uses [HTTP]
Rel_R(flask_data, datos_gov, "Uses")

@enduml
