@startuml
'https://plantuml.com/class-diagram

node AndroidApplication <<Kotlin>> {
    namespace view {
        class ChatbotFragment  {
        }
    }
}

node Chatbot <<Flask>> {
    namespace python-chatbot.src {
        class ChatbotModel {
            + clean_up_sentence(): List sentence_words
            + prediction_calculation(message): List results
            + bag_of_words(): Array bag
            + get_response(sentence): String response
        }
        class controller {
            + get_response(): String message
        }
        class TrainBot {
            + train_bot(): String status
        }

        controller *- ChatbotModel
        view.ChatbotFragment o-- controller
        ChatbotModel *-- TrainBot
    }
}
@enduml