@startuml
'https://plantuml.com/class-diagram


node AndroidApplication <<Kotlin>> {
    namespace view {
        class VarietyResumeFragment  {
            + onCreateView(): View?
        }
    }
}

package CIAT_Dataverse <<Rectangle>> {
}
node GraphData <<Flask>> {
    namespace rice-graph.src {
        class graph_processing {
            + _ _init_ _ (): void
            + predict_yield(DataFrame df_saldana_harvest): GraphData
            + graph_data_by_variety(String variety): GraphData
        }
        class GraphController {
            + graph_processing : GraphProcessing
            + graph_data(): void
        }
        class GraphData {
            + line_set: dict
            + min_temp: String
            + max_temp: String
            + rhum: String
            + sbright: String
            + prec: String
            + prod: String
        }
        interface IDataReader {
            get_data(): DataFrame data
        }
        class DataReader {
            get_data(): DataFrame data
        }

        graph_processing o-- GraphData
        IDataReader <|-- DataReader  :implements
        DataReader -- CIAT_Dataverse
        GraphController o- graph_processing
        view.VarietyResumeFragment o-- GraphController
        graph_processing -- IDataReader
    }
}

@enduml