@startuml
'https://plantuml.com/class-diagram


node Android_application <<Kotlin>> {
    namespace view.login {
        class LoginActivity  {
            onCreate()
        }
        class RegisterActivity  {
            onCreate()
        }
    }
}

package MySQL <<Database>> {
}

node Authorization_service <<Flask>> {
    namespace data.user {
        class UserController {
        }
        class UserManager {
            loginUser(User user)
            registerUser(User user)
            getCurrentUser(User user)
            logoutUser(User user)
        }
        class UserModel {
        }
        class User {
            name: String
            password: String
        }
        interface IUserDAO {
            getUser(User user)
            createUser(User user)
            update(User user)
            delete(User user)
        }
        class UserDAO {
            getUser(User user)
            createUser(User user)
            update(User user)
            delete(User user)
        }

        UserManager o-- User
        IUserDAO  <|-- UserDAO :implements
        UserDAO -- MySQL
        view.login.LoginActivity o-- UserController
        UserModel o- UserManager
        UserModel -o UserController
        UserController -o view.login.RegisterActivity
        UserController o-- UserManager
        UserManager -- IUserDAO
    }
}

@enduml