@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam packageStyle rect

actor User as user
note "Graphs according to\nuser's seed selection" as graphNote

package System{
    (Process precipitation) as prec
    (Process relative humidity) as rhum
    (Process sun bright) as sbright
    (Process maximum\nor minimum\nair temperature) as (temp)
    (Process production) as (prod)

    (Process graph data) as historic
    (Fetch data) as fetch
    (Graph data) as graph

    user -- graph
    (graph) .. graphNote
    historic <. graph: include
    historic ..> fetch: include

    historic ..> prec :include
    historic ..> rhum :include
    historic ..> sbright :include
    historic ..> temp :include
    historic ..> prod :include
}

@enduml