@startuml
'https://plantuml.com/use-case-diagram
left to right direction


package System{
    (Register new user) as signup
    (Login user) as login

    (Fetch data) as fetch
    (Register data) as register
    (Get data) as consult
}

User -> (login)
User -> (signup)

(login) -- fetch
(signup) -- fetch

fetch -- register
fetch -- consult

note "User can only register\nwith email" as N1
(User) -- N1
N1 -- (signup)

@enduml