@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam packageStyle rect

actor Chatbot as chat
actor User as user

package System{
    (Communicate with bot) as historic

    user -- historic

    (Graph data) as graph
    (Show data) as show_data
    (Process graph data) as fetch

    show_data <. graph :includes
    graph .> fetch :includes
}

chat -- graph
@enduml