@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam packageStyle rect

actor User as user

package System{
    (Graph precipitation) as prec
    (Graph relative humidity) as rhum
    (Graph sun bright) as sbright
    (Graph maximum\nor minimum\nair temperature) as (temp)

    (Get historic data) as historic

    user -- historic

    historic <.. prec :extends
    historic <.. rhum :extends
    historic <.. sbright :extends
    historic <.. temp :extends
}

@enduml